### ISSUE TITLE
Lien Concessionnaire - Marque manquant

### ISSUE THREAD

**Issue by sixdouglas** [denisjunior/TP_VenteDeVoiture#2]
Il manque le lien n-n entre Concessionnaire et Marque dans le mapping des entités

**Comment by denisjunior** [comment]
Bonjour Monsieur, hier après vos remarques j'ai fait des update. Vous
pouvez revoir mon repo (denisjunior)  merci.
cordialement

Le lun. 9 nov. 2020 à 21:20, SIX Douglas <notifications@github.com> a
écrit :
